version: 2
jobs:
  build:
    working_directory: ~/spinners
    docker:
      - image: circleci/node:12.11.1
    branches:
      only:
        - master
    steps:
      - checkout

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/spinners/.npmrc

      - run:
          name: Publishing NPM Package
          command: npm publish

      - run:
          name: Installing dependenices for GitHub Release
          command: yarn install --frozen-lockfile

      - run:
          name: Setup GitHub for Release
          command: git config --global -l && git config --global user.email $GIT_EMAIL && git config --global user.name $GIT_NAME

      - run:
          name: Publishing GitHub Release
          command: npm run github-release
