version: 2
jobs:
  build:
    working_directory: ~/spinners
    docker:
      - image: circleci/golang:1.13.1-node
    branches:
      only:
        - master
    steps:
      - checkout

      - run:
          name: Adding Github Release
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(npm view scss-spinners version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} ./dist/

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/spinners/.npmrc

      - run:
          name: Publishing NPM Package
          command: npm publish
