version: 2
jobs:
  npm:
    working_directory: ~/spinners
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/spinners/.npmrc

      - run:
          name: Publishing NPM Package
          command: npm publish

      - run:
          name: Publishing Github Release
          command: npm run github-release

workflows:
  version: 2
  build:
    jobs:
      - npm:
          filters:
            branches:
              only: master
