version: 2
jobs:
  npm:
    working_directory: ~/spinners
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/spinners/.npmrc

      - run:
          name: Publishing NPM Package
          command: npm publish

  github:
    docker:
      - image: circleci/golang:1.13.1-node
    steps:
      - checkout

      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(npm view scss-spinners version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} ./dist/

workflows:
  version: 2
  build:
    jobs:
      # - npm
      #     filters:
      #       branches:
      #         only: master
      - github:
          filters:
            branches:
              only: master
