version: 2
jobs:
  npm:
    working_directory: ~/spinners
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/spinners/.npmrc

      - run:
          name: Publishing NPM Package
          command: npm publish

  github:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout

      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(npm view scss-spinners version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./dist/

workflows:
  version: 2
  build:
    branches:
      only:
        - master
    jobs:
      # - npm
      - github
